Eventos Parque: 

->Cliente Nº 1 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:0 
-----------------------------------------------------
->Cliente Nº 1 Entrou no Parque As: 0:0:1 
-----------------------------------------------------
->Cliente Nº 1 (28) Chegou a Fila da Piscina As: 0:0:3 
-----------------------------------------------------
->Cliente Nº 2 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:4 
-----------------------------------------------------
->Cliente Nº 2 Entrou no Parque As: 0:0:5 
-----------------------------------------------------
->Cliente Nº 2 (23) Chegou a Fila da Piscina As: 0:0:6 
-----------------------------------------------------
->Cliente Nº 4 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:0:7 
-----------------------------------------------------
->Cliente Nº 4 Entrou no Parque As: 0:0:8 
-----------------------------------------------------
->Cliente Nº 4 Chegou a Fila do Escorrega As: 0:0:9 
-----------------------------------------------------
->Cliente Nº 1 (28) Entrou na Piscina As: 0:0:10 
-----------------------------------------------------
->Cliente Nº 6 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:11 
-----------------------------------------------------
->Cliente Nº 6 Entrou no Parque As: 0:0:12 
-----------------------------------------------------
->Cliente Nº 6 (61) Chegou a Fila da Piscina As: 0:0:13 
-----------------------------------------------------
->Cliente Nº 8 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:14 
-----------------------------------------------------
->Cliente Nº 8 Entrou no Parque As: 0:0:15 
-----------------------------------------------------
->Cliente Nº 8 (35) Chegou a Fila da Piscina As: 0:0:16 
-----------------------------------------------------
->Cliente Nº 10 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:17 
-----------------------------------------------------
->Cliente Nº 10 Entrou no Parque As: 0:0:18 
-----------------------------------------------------
->Cliente Nº 10 Chegou a Fila do Escorrega As: 0:0:19 
-----------------------------------------------------
->Cliente Nº 10 Andou no Escorrega As: 0:0:20 
-----------------------------------------------------
->Cliente Nº 7 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:21 
-----------------------------------------------------
->Cliente Nº 7 Entrou no Parque As: 0:0:22 
-----------------------------------------------------
->Cliente Nº 7 (46) Chegou a Fila da Piscina As: 0:0:23 
-----------------------------------------------------
->Cliente Nº 14 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:24 
-----------------------------------------------------
->Cliente Nº 14 Entrou no Parque As: 0:0:25 
-----------------------------------------------------
->Cliente Nº 14 (28) Chegou a Fila da Piscina As: 0:0:26 
-----------------------------------------------------
->Cliente Nº 16 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:27 
-----------------------------------------------------
->Cliente Nº 16 Entrou no Parque As: 0:0:28 
-----------------------------------------------------
->Cliente Nº 16 Chegou a Fila do Escorrega As: 0:0:29 
-----------------------------------------------------
->Cliente Nº 18 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:30 
-----------------------------------------------------
->Cliente Nº 18 Entrou no Parque As: 0:0:31 
-----------------------------------------------------
->Cliente Nº 18 Chegou a Fila do Escorrega As: 0:0:32 
-----------------------------------------------------
->Cliente Nº 2 (23) Entrou na Piscina As: 0:0:33 
-----------------------------------------------------
->Cliente Nº 20 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:34 
-----------------------------------------------------
->Cliente Nº 20 Entrou no Parque As: 0:0:35 
-----------------------------------------------------
->Cliente Nº 20 Chegou a Fila do Escorrega As: 0:0:36 
-----------------------------------------------------
->Cliente Nº 21 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:37 
-----------------------------------------------------
->Cliente Nº 21 Entrou no Parque As: 0:0:38 
-----------------------------------------------------
->Cliente Nº 21 (22) Chegou a Fila da Piscina As: 0:0:39 
-----------------------------------------------------
->Cliente Nº 23 ((MR)) Chegou a  Fila das Bilheteiras As: 0:0:40 
-----------------------------------------------------
->Cliente Nº 23 Entrou no Parque As: 0:0:41 
-----------------------------------------------------
->Cliente Nº 23 (56) Chegou a Fila da Piscina As: 0:0:42 
-----------------------------------------------------
->Cliente Nº 25 ((MR)) Chegou a  Fila das Bilheteiras As: 0:0:43 
-----------------------------------------------------
->Cliente Nº 25 Entrou no Parque As: 0:0:44 
-----------------------------------------------------
->Cliente Nº 25 Chegou a Fila do Bar As: 0:0:45 
-----------------------------------------------------
->Cliente Nº 25 Foi Atendido no Bar As: 0:0:46 E Ficou no Bar 
-----------------------------------------------------
->Cliente Nº 9 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:0:47 
-----------------------------------------------------
->Cliente Nº 9 Entrou no Parque As: 0:0:48 
-----------------------------------------------------
->Cliente Nº 9 (8) Chegou a Fila da Piscina As: 0:0:49 
-----------------------------------------------------
->Cliente Nº 5 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:50 
-----------------------------------------------------
->Cliente Nº 5 Entrou no Parque As: 0:0:51 
-----------------------------------------------------
->Cliente Nº 5 (20) Chegou a Fila da Piscina As: 0:0:52 
-----------------------------------------------------
->Cliente Nº 30 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:53 
-----------------------------------------------------
->Cliente Nº 30 Entrou no Parque As: 0:0:54 
-----------------------------------------------------
->Cliente Nº 30 (78) Chegou a Fila da Piscina As: 0:0:55 
-----------------------------------------------------
->Cliente Nº 11 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:56 
-----------------------------------------------------
->Cliente Nº 11 Entrou no Parque As: 0:0:57 
-----------------------------------------------------
->Cliente Nº 11 (24) Chegou a Fila da Piscina As: 0:0:58 
-----------------------------------------------------
->Cliente Nº 33 ((PG)) Chegou a  Fila das Bilheteiras As: 0:0:59 
-----------------------------------------------------
->Cliente Nº 33 Entrou no Parque As: 0:1:0 
-----------------------------------------------------
->Cliente Nº 33 Saiu do Parque As: 0:1:1 
-----------------------------------------------------
->Cliente Nº 35 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:2 
-----------------------------------------------------
->Cliente Nº 35 Entrou no Parque As: 0:1:3 
-----------------------------------------------------
->Cliente Nº 35 (67) Chegou a Fila da Piscina As: 0:1:4 
-----------------------------------------------------
->Cliente Nº 4 Andou no Escorrega As: 0:1:5 
-----------------------------------------------------
->Cliente Nº 37 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:1:6 
-----------------------------------------------------
->Cliente Nº 37 Entrou no Parque As: 0:1:7 
-----------------------------------------------------
->Cliente Nº 37 Saiu do Parque As: 0:1:8 
-----------------------------------------------------
->Cliente Nº 39 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:9 
-----------------------------------------------------
->Cliente Nº 39 Entrou no Parque As: 0:1:10 
-----------------------------------------------------
->Cliente Nº 39 Chegou a Fila do Escorrega As: 0:1:11 
-----------------------------------------------------
->Cliente Nº 41 ((MR)) Chegou a  Fila das Bilheteiras As: 0:1:12 
-----------------------------------------------------
->Cliente Nº 41 Entrou no Parque As: 0:1:13 
-----------------------------------------------------
->Cliente Nº 41 Chegou a Fila do Bar As: 0:1:14 
-----------------------------------------------------
->Cliente Nº 41 Foi Atendido no Bar As: 0:1:15 e Saiu do Bar 
-----------------------------------------------------
->Cliente Nº 41 (62) Chegou a Fila da Piscina As: 0:1:16 
-----------------------------------------------------
->Cliente Nº 23 (56) Entrou na Piscina As: 0:1:17 
-----------------------------------------------------
->Cliente Nº 44 ((MR)) Chegou a  Fila das Bilheteiras As: 0:1:18 
-----------------------------------------------------
->Cliente Nº 44 Entrou no Parque As: 0:1:19 
-----------------------------------------------------
->Cliente Nº 44 (63) Chegou a Fila da Piscina As: 0:1:20 
-----------------------------------------------------
->Cliente Nº 15 ((MR)) Chegou a  Fila das Bilheteiras As: 0:1:21 
-----------------------------------------------------
->Cliente Nº 15 Entrou no Parque As: 0:1:22 
-----------------------------------------------------
->Cliente Nº 15 (59) Chegou a Fila da Piscina As: 0:1:23 
-----------------------------------------------------
->Cliente Nº 47 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:24 
-----------------------------------------------------
->Cliente Nº 47 Entrou no Parque As: 0:1:25 
-----------------------------------------------------
->Cliente Nº 47 Saiu do Parque As: 0:1:26 
-----------------------------------------------------
->Cliente Nº 49 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:1:27 
-----------------------------------------------------
->Cliente Nº 49 Entrou no Parque As: 0:1:28 
-----------------------------------------------------
->Cliente Nº 49 Saiu do Parque As: 0:1:29 
-----------------------------------------------------
->Cliente Nº 50 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:30 
-----------------------------------------------------
->Cliente Nº 50 Entrou no Parque As: 0:1:31 
-----------------------------------------------------
->Cliente Nº 50 (35) Chegou a Fila da Piscina As: 0:1:32 
-----------------------------------------------------
->Cliente Nº 29 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:33 
-----------------------------------------------------
->Cliente Nº 29 Entrou no Parque As: 0:1:34 
-----------------------------------------------------
->Cliente Nº 29 Saiu do Parque As: 0:1:35 
-----------------------------------------------------
->Cliente Nº 53 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:1:36 
-----------------------------------------------------
->Cliente Nº 53 Entrou no Parque As: 0:1:37 
-----------------------------------------------------
->Cliente Nº 53 Saiu do Parque As: 0:1:38 
-----------------------------------------------------
->Cliente Nº 55 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:39 
-----------------------------------------------------
->Cliente Nº 55 Entrou no Parque As: 0:1:40 
-----------------------------------------------------
->Cliente Nº 55 Saiu do Parque As: 0:1:41 
-----------------------------------------------------
->Cliente Nº 57 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:42 
-----------------------------------------------------
->Cliente Nº 57 Entrou no Parque As: 0:1:43 
-----------------------------------------------------
->Cliente Nº 57 Saiu do Parque As: 0:1:44 
-----------------------------------------------------
->Cliente Nº 19 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:45 
-----------------------------------------------------
->Cliente Nº 19 Entrou no Parque As: 0:1:46 
-----------------------------------------------------
->Cliente Nº 19 Chegou a Fila do Bar As: 0:1:47 
-----------------------------------------------------
->Cliente Nº 19 Foi Atendido no Bar As: 0:1:48 e Saiu do Bar 
-----------------------------------------------------
->Cliente Nº 19 (77) Chegou a Fila da Piscina As: 0:1:49 
-----------------------------------------------------
->Cliente Nº 12 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:50 
-----------------------------------------------------
->Cliente Nº 12 Entrou no Parque As: 0:1:51 
-----------------------------------------------------
->Cliente Nº 12 Saiu do Parque As: 0:1:52 
-----------------------------------------------------
->Cliente Nº 38 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:53 
-----------------------------------------------------
->Cliente Nº 38 Entrou no Parque As: 0:1:54 
-----------------------------------------------------
->Cliente Nº 38 Saiu do Parque As: 0:1:55 
-----------------------------------------------------
->Cliente Nº 13 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:56 
-----------------------------------------------------
->Cliente Nº 13 Entrou no Parque As: 0:1:57 
-----------------------------------------------------
->Cliente Nº 13 Saiu do Parque As: 0:1:58 
-----------------------------------------------------
->Cliente Nº 3 ((PG)) Chegou a  Fila das Bilheteiras As: 0:1:59 
-----------------------------------------------------
->Cliente Nº 3 Entrou no Parque As: 0:2:0 
-----------------------------------------------------
->Cliente Nº 3 Saiu do Parque As: 0:2:1 
-----------------------------------------------------
->Cliente Nº 24 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:2 
-----------------------------------------------------
->Cliente Nº 24 Entrou no Parque As: 0:2:3 
-----------------------------------------------------
->Cliente Nº 24 Saiu do Parque As: 0:2:4 
-----------------------------------------------------
->Cliente Nº 16 Desistiu da Fila do Escorrega As: 0:2:5 
-----------------------------------------------------
->Cliente Nº 10 Chegou a Fila do Bar As: 0:2:6 
-----------------------------------------------------
->Cliente Nº 45 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:7 
-----------------------------------------------------
->Cliente Nº 45 Entrou no Parque As: 0:2:8 
-----------------------------------------------------
->Cliente Nº 46 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:2:9 
-----------------------------------------------------
->Cliente Nº 46 Entrou no Parque As: 0:2:10 
-----------------------------------------------------
->Cliente Nº 48 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:11 
-----------------------------------------------------
->Cliente Nº 48 Entrou no Parque As: 0:2:12 
-----------------------------------------------------
->Cliente Nº 20 Desistiu da Fila do Escorrega As: 0:2:13 
-----------------------------------------------------
->Cliente Nº 2 (23) Saiu da Piscina As: 0:2:14 
-----------------------------------------------------
->Cliente Nº 21 (22) Desistiu da Fila da Piscina As: 0:2:15 
-----------------------------------------------------
->Cliente Nº 28 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:16 
-----------------------------------------------------
->Cliente Nº 28 Entrou no Parque As: 0:2:17 
-----------------------------------------------------
->Cliente Nº 51 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:18 
-----------------------------------------------------
->Cliente Nº 51 Entrou no Parque As: 0:2:19 
-----------------------------------------------------
->Cliente Nº 23 (56) Saiu da Piscina As: 0:2:20 
-----------------------------------------------------
->Cliente Nº 17 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:21 
-----------------------------------------------------
->Cliente Nº 17 Entrou no Parque As: 0:2:22 
-----------------------------------------------------
->Cliente Nº 1 (28) Saiu da Piscina As: 0:2:23 
-----------------------------------------------------
->Cliente Nº 31 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:24 
-----------------------------------------------------
->Cliente Nº 31 Entrou no Parque As: 0:2:25 
-----------------------------------------------------
->Cliente Nº 5 (20) Desistiu da Fila da Piscina As: 0:2:26 
-----------------------------------------------------
->Cliente Nº 32 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:27 
-----------------------------------------------------
->Cliente Nº 32 Entrou no Parque As: 0:2:28 
-----------------------------------------------------
->Cliente Nº 30 (78) Desistiu da Fila da Piscina As: 0:2:29 
-----------------------------------------------------
->Cliente Nº 30 Saiu do Parque As: 0:2:30 
-----------------------------------------------------
->Cliente Nº 60 ((Cri)) Chegou a  Fila das Bilheteiras As: 0:2:31 
-----------------------------------------------------
->Cliente Nº 60 Entrou no Parque As: 0:2:32 
-----------------------------------------------------
->Cliente Nº 60 Saiu do Parque As: 0:2:33 
-----------------------------------------------------
->Cliente Nº 6 (61) Entrou na Piscina As: 0:2:34 
-----------------------------------------------------
->Cliente Nº 36 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:35 
-----------------------------------------------------
->Cliente Nº 36 Entrou no Parque As: 0:2:36 
-----------------------------------------------------
->Cliente Nº 36 Saiu do Parque As: 0:2:37 
-----------------------------------------------------
->Cliente Nº 22 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:38 
-----------------------------------------------------
->Cliente Nº 22 Entrou no Parque As: 0:2:39 
-----------------------------------------------------
->Cliente Nº 22 Saiu do Parque As: 0:2:40 
-----------------------------------------------------
->Cliente Nº 25 Saiu da Sala do Bar As: 0:2:41 
-----------------------------------------------------
->Cliente Nº 25 Saiu do Parque As: 0:2:42 
-----------------------------------------------------
->Cliente Nº 39 Desistiu da Fila do Escorrega As: 0:2:43 
-----------------------------------------------------
->Cliente Nº 39 Saiu do Parque As: 0:2:44 
-----------------------------------------------------
->Cliente Nº 14 (28) Desistiu da Fila da Piscina As: 0:2:45 
-----------------------------------------------------
->Cliente Nº 14 Saiu do Parque As: 0:2:46 
-----------------------------------------------------
->Cliente Nº 41 (62) Desistiu da Fila da Piscina As: 0:2:47 
-----------------------------------------------------
->Cliente Nº 41 Saiu do Parque As: 0:2:48 
-----------------------------------------------------
->Cliente Nº 18 Desistiu da Fila do Escorrega As: 0:2:49 
-----------------------------------------------------
->Cliente Nº 18 Saiu do Parque As: 0:2:50 
-----------------------------------------------------
->Cliente Nº 44 (63) Desistiu da Fila da Piscina As: 0:2:51 
-----------------------------------------------------
->Cliente Nº 44 Saiu do Parque As: 0:2:52 
-----------------------------------------------------
->Cliente Nº 46 Saiu do Parque As: 0:2:53 
-----------------------------------------------------
->Cliente Nº 27 ((PG)) Chegou a  Fila das Bilheteiras As: 0:2:54 
-----------------------------------------------------
->Cliente Nº 27 Entrou no Parque As: 0:2:55 
-----------------------------------------------------
->Cliente Nº 27 Saiu do Parque As: 0:2:56 
-----------------------------------------------------
->Cliente Nº 20 Saiu do Parque As: 0:2:57 
-----------------------------------------------------
->Cliente Nº 2 Chegou a Fila do Bar As: 0:2:58 
-----------------------------------------------------
->Cliente Nº 21 Saiu do Parque As: 0:2:59 
-----------------------------------------------------
->Cliente Nº 9 (8) Entrou na Piscina As: 0:3:0 
-----------------------------------------------------
->Cliente Nº 28 Saiu do Parque As: 0:3:1 
-----------------------------------------------------
->Cliente Nº 52 ((MR)) Chegou a  Fila das Bilheteiras As: 0:3:2 
-----------------------------------------------------
->Cliente Nº 52 Entrou no Parque As: 0:3:3 
-----------------------------------------------------
->Cliente Nº 52 Saiu do Parque As: 0:3:4 
-----------------------------------------------------
->Cliente Nº 50 (35) Desistiu da Fila da Piscina As: 0:3:5 
-----------------------------------------------------
->Cliente Nº 50 Saiu do Parque As: 0:3:6 
-----------------------------------------------------
->Cliente Nº 17 Saiu do Parque As: 0:3:7 
-----------------------------------------------------
->Cliente Nº 1 Saiu do Parque As: 0:3:8 
-----------------------------------------------------
->Cliente Nº 56 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:9 
-----------------------------------------------------
->Cliente Nº 56 Entrou no Parque As: 0:3:10 
-----------------------------------------------------
->Cliente Nº 56 Saiu do Parque As: 0:3:11 
-----------------------------------------------------
->Cliente Nº 58 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:12 
-----------------------------------------------------
->Cliente Nº 58 Entrou no Parque As: 0:3:13 
-----------------------------------------------------
->Cliente Nº 58 Saiu do Parque As: 0:3:14 
-----------------------------------------------------
->Cliente Nº 59 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:15 
-----------------------------------------------------
->Cliente Nº 59 Entrou no Parque As: 0:3:16 
-----------------------------------------------------
->Cliente Nº 59 Saiu do Parque As: 0:3:17 
-----------------------------------------------------
->Cliente Nº 8 (35) Desistiu da Fila da Piscina As: 0:3:18 
-----------------------------------------------------
->Cliente Nº 8 Saiu do Parque As: 0:3:19 
-----------------------------------------------------
->Cliente Nº 19 (77) Desistiu da Fila da Piscina As: 0:3:20 
-----------------------------------------------------
->Cliente Nº 19 Saiu do Parque As: 0:3:21 
-----------------------------------------------------
->Cliente Nº 40 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:22 
-----------------------------------------------------
->Cliente Nº 40 Entrou no Parque As: 0:3:23 
-----------------------------------------------------
->Cliente Nº 40 Saiu do Parque As: 0:3:24 
-----------------------------------------------------
->Cliente Nº 6 (61) Saiu da Piscina As: 0:3:25 
-----------------------------------------------------
->Cliente Nº 6 Saiu do Parque As: 0:3:26 
-----------------------------------------------------
->Cliente Nº 10 Foi Atendido no Bar As: 0:3:27 e Saiu do Bar 
-----------------------------------------------------
->Cliente Nº 10 Saiu do Parque As: 0:3:28 
-----------------------------------------------------
->Cliente Nº 26 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:29 
-----------------------------------------------------
->Cliente Nº 26 Entrou no Parque As: 0:3:30 
-----------------------------------------------------
->Cliente Nº 26 Saiu do Parque As: 0:3:31 
-----------------------------------------------------
->Cliente Nº 51 Chegou a Fila do Bar As: 0:3:32 
-----------------------------------------------------
->Cliente Nº 23 Saiu do Parque As: 0:3:33 
-----------------------------------------------------
->Cliente Nº 54 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:34 
-----------------------------------------------------
->Cliente Nº 54 Entrou no Parque As: 0:3:35 
-----------------------------------------------------
->Cliente Nº 54 Saiu do Parque As: 0:3:36 
-----------------------------------------------------
->Cliente Nº 32 Saiu do Parque As: 0:3:37 
-----------------------------------------------------
->Cliente Nº 16 Saiu do Parque As: 0:3:38 
-----------------------------------------------------
->Cliente Nº 11 (24) Desistiu da Fila da Piscina As: 0:3:39 
-----------------------------------------------------
->Cliente Nº 11 Saiu do Parque As: 0:3:40 
-----------------------------------------------------
->Cliente Nº 35 (67) Desistiu da Fila da Piscina As: 0:3:41 
-----------------------------------------------------
->Cliente Nº 35 Saiu do Parque As: 0:3:42 
-----------------------------------------------------
->Cliente Nº 7 (46) Desistiu da Fila da Piscina As: 0:3:43 
-----------------------------------------------------
->Cliente Nº 7 Saiu do Parque As: 0:3:44 
-----------------------------------------------------
->Cliente Nº 43 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:45 
-----------------------------------------------------
->Cliente Nº 43 Entrou no Parque As: 0:3:46 
-----------------------------------------------------
->Cliente Nº 43 Saiu do Parque As: 0:3:47 
-----------------------------------------------------
->Cliente Nº 15 (59) Desistiu da Fila da Piscina As: 0:3:48 
-----------------------------------------------------
->Cliente Nº 15 Saiu do Parque As: 0:3:49 
-----------------------------------------------------
->Cliente Nº 48 Saiu do Parque As: 0:3:50 
-----------------------------------------------------
->Cliente Nº 31 Saiu do Parque As: 0:3:51 
-----------------------------------------------------
->Cliente Nº 5 Saiu do Parque As: 0:3:52 
-----------------------------------------------------
->Cliente Nº 34 ((PG)) Chegou a  Fila das Bilheteiras As: 0:3:53 
-----------------------------------------------------
->Cliente Nº 34 Entrou no Parque As: 0:3:54 
-----------------------------------------------------
->Cliente Nº 34 Saiu do Parque As: 0:3:55 
-----------------------------------------------------
->Cliente Nº 45 Saiu do Parque As: 0:3:56 
-----------------------------------------------------
->Cliente Nº 2 Foi Atendido no Bar As: 0:3:57 e Saiu do Bar 
-----------------------------------------------------
->Cliente Nº 2 Saiu do Parque As: 0:3:58 
-----------------------------------------------------
->Cliente Nº 4 (17) Chegou a Fila da Piscina As: 0:3:59 
-----------------------------------------------------
->Cliente Nº 42 ((PG)) Chegou a  Fila das Bilheteiras As: 0:4:0 
-----------------------------------------------------
->Cliente Nº 42 Entrou no Parque As: 0:4:1 
-----------------------------------------------------
->Cliente Nº 42 Saiu do Parque As: 0:4:2 
-----------------------------------------------------
->Cliente Nº 4 (17) Entrou na Piscina As: 0:4:3 
-----------------------------------------------------
->Cliente Nº 9 (8) Saiu da Piscina As: 0:4:4 
-----------------------------------------------------
->Cliente Nº 9 Saiu do Parque As: 0:4:5 
-----------------------------------------------------
->Cliente Nº 51 Foi Atendido no Bar As: 0:4:6 e Saiu do Bar 
-----------------------------------------------------
->Cliente Nº 51 Saiu do Parque As: 0:4:7 
-----------------------------------------------------
->Cliente Nº 4 (17) Saiu da Piscina As: 0:4:24 
-----------------------------------------------------
->Cliente Nº 4 Saiu do Parque As: 0:4:25 
-----------------------------------------------------
*Simulacao Terminada* 

